version: "3.9"
services:
  web:
    build:
      context: ./
    command: python ../manage.py runserver 0.0.0.0:8000
    container_name: web
    volumes:
      - ./:/Users/sujalbhakare1012/Documents/backend/portfolio_backend
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork
  db:
    image: postgres:14.1-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - djangonetwork
volumes:
  postgres_data:
networks:
  djangonetwork:
    driver: bridge
