# Generated by Django 4.2.1 on 2023-06-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_comment_alter_contact_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='comment',
            field=models.TextField(blank=True, editable=False, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='reason',
            field=models.CharField(choices=[('GENERAL', 'General'), ('HIRING', 'Hiring'), ('CONSULT', 'Consult'), ('OTHER', 'Other')], default='JANUARY', editable=False, max_length=30),
        ),
    ]
