# Generated by Django 4.2.1 on 2023-06-07 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('poster', models.URLField(null=True)),
                ('author', models.CharField(max_length=100)),
                ('author_avatar', models.URLField(null=True)),
                ('edited_on', models.DateTimeField(editable=False)),
                ('slug', models.SlugField(default='', editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='', editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='', editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BlogViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_on', models.DateTimeField(auto_created=True)),
                ('visitor', models.GenericIPAddressField()),
                ('blog_modal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
        ),
        migrations.CreateModel(
            name='BlogLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_on', models.DateTimeField(auto_created=True)),
                ('liker', models.GenericIPAddressField()),
                ('blog_modal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(null=True, to='blog.category'),
        ),
        migrations.AddField(
            model_name='blog',
            name='external_links',
            field=models.ManyToManyField(null=True, to='blog.externallinks'),
        ),
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(null=True, to='blog.bloglike'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(null=True, to='blog.tags'),
        ),
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.ManyToManyField(to='blog.blogviews'),
        ),
    ]
