# Generated by Django 4.2.1 on 2023-06-07 08:44

from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=django_editorjs_fields.fields.EditorJsJSONField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(blank=True, to='blog.category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_on',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='external_links',
            field=models.ManyToManyField(blank=True, to='blog.externallinks'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(blank=True, to='blog.bloglike'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.tags'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='views',
            field=models.ManyToManyField(blank=True, to='blog.blogviews'),
        ),
        migrations.AlterField(
            model_name='bloglike',
            name='liked_on',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='blogviews',
            name='visited_on',
            field=models.DateTimeField(editable=False),
        ),
    ]
