# Generated by Django 4.2.1 on 2023-06-07 08:46

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_body_alter_blog_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=django_editorjs_fields.fields.EditorJsTextField(),
        ),
    ]
