# Generated by Django 4.2.1 on 2023-06-09 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_bloglike_blog_modal_alter_bloglike_liker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglike',
            name='blog_modal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
        ),
        migrations.AlterField(
            model_name='bloglike',
            name='liker',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='blogviews',
            name='blog_modal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
        ),
        migrations.AlterField(
            model_name='blogviews',
            name='visitor',
            field=models.GenericIPAddressField(),
        ),
    ]
