# Generated by Django 4.2.1 on 2023-06-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.URLField(null=True)),
                ('docs', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_price', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('created_on', models.DateTimeField()),
                ('poster', models.URLField(null=True)),
                ('slug', models.SlugField(default='', editable=False, max_length=100)),
                ('tech_stack', models.ManyToManyField(blank=True, to='service.programmingtech')),
            ],
        ),
    ]
