# Generated by Django 4.2.1 on 2023-06-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_serviceenquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceenquiry',
            name='created_on',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='services',
            name='created_on',
            field=models.DateTimeField(editable=False),
        ),
    ]
