# Generated by Django 4.2.1 on 2023-06-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
