# Generated by Django 4.2.1 on 2023-06-06 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='deadline_for_priceDrop',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='price_after_deadline',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courses',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='courses',
            name='video',
            field=models.FileField(null=True, upload_to='courses-videos'),
        ),
    ]
