# Generated by Django 4.2.1 on 2023-06-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courses_image_link_courses_video_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/courses-poster'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/courses-videos'),
        ),
    ]
