# Generated by Django 4.2.1 on 2023-06-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('courses', '0006_alter_courses_poster_alter_courses_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='technology',
        ),
        migrations.AddField(
            model_name='courses',
            name='technology',
            field=models.ManyToManyField(blank=True, null=True, to='service.programmingtech'),
        ),
    ]
