# Generated by Django 4.2.1 on 2023-06-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_courses_technology_courses_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseintrest',
            name='date_added',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='created_on',
            field=models.DateTimeField(editable=False),
        ),
    ]
