# Generated by Django 4.2.1 on 2023-06-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_serviceenquiry_created_on_and_more'),
        ('courses', '0008_alter_courseintrest_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='technology',
            field=models.ManyToManyField(blank=True, to='service.programmingtech'),
        ),
    ]
