# Generated by Django 4.2.1 on 2023-06-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_data', '0002_alter_webvisits_visited'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date_added', models.DateTimeField(editable=False)),
                ('subscribed', models.BooleanField(default=True)),
            ],
        ),
    ]
