# Generated by Django 4.2.1 on 2023-06-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_data', '0003_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webvisits',
            name='ip_address',
            field=models.GenericIPAddressField(editable=False),
        ),
        migrations.AlterField(
            model_name='webvisits',
            name='page',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
    ]
